import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // 'Home',
    // {
    //   type: 'html',
    //   value: '<span style="opacity: 0.6; font-size: 14px; color:#FD5C04;">Management</span>'
    // },
    {
      type: 'category',
      label: 'Product',
      items: [
        {
          type: 'category',
          label: 'Product list',
          link: {
            type: 'doc',
            id: 'Product/Product/Product_list'
          }
          ,
          items: [
            'Product/Product/Product',
            'Product/Product/Option',
            'Product/Product/Filter',
            'Product/Product/Button_Action'
          ],
          
        },
        
        // 'Product/Availability',
        // 'Product/SpecialOffer',
        {
          type: 'category',
          label: 'Manage Discount',
          link: {
            type: 'doc',
            id: 'Product/ManageDiscount/ManageDiscount'
          }
          ,
          items: [
            'Product/ManageDiscount/Creatediscount',
            'Product/ManageDiscount/Filter',
            'Product/ManageDiscount/Action',
          ],
          
        },
        
      ],
    }
    ,
    {
      type: 'category',
      label: 'Bookings',
      items: [
        {
          type:'doc',
          id:'Booking/Status'
        }
        ,
        {
          type:'doc',
          id:'Booking/Bookings'
        }
      ]
    }
      ,   
    // {
    //   type: 'category',
    //   label: 'Performance',
    //   items: ['Performance/Reviews', 'Performance/Analytics'],
    // }
    // ,
// 'Finance',
    { // ขีดเส้นใต้
  type: 'html',
      value: '<hr style="border-color: black; margin: 8px 0;">',
    }, 
'Account'
  ],
};

export default sidebars;
